name = "mathcastle"
compatibility_date = "2024-12-01"
pages_build_output_dir = "./"

[[d1_databases]]
binding = "DB"
database_name = "mathcastle-db"
database_id = "8e82137a-da8f-47d5-b6ad-b57ecb9741e2"
